version: "3.6"

services:
  rundeckdb:
    image: mysql:5.7
    volumes:
      - /opt/DATA/mysql:/var/lib/mysql
    environment:
#      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=rundeck
    ports:
      - "3306:3306"
    networks:
      - rundeck-network

  rundeck:
    image: 0x539samy/rundeck
    depends_on:
      - rundeckdb
    volumes:
      - /opt/DATA/rundeck/projects:/var/rundeck/projects
      - /opt/DATA/rundeck/var:/var/lib/rundeck/var
      - /opt/DATA/rundeck/logs:/var/lib/rundeck/logs
      - /opt/rundeck/data:/var/lib/rundeck/data
      - /opt/rundeck/plugins:/var/lib/rundeck/libext
      - /run/docker.sock:/var/run/docker.sock
    networks:
      - rundeck-network

    environment:
      - DEFAULT_ADMIN_USER=admin
      - DEFAULT_ADMIN_PASSWORD=admin
      - DEFAULT_USER=CHANGEME
      - DEFAULT_PASSWORD=CHANGEME
      - SERVER_URL=http://0.0.0.0:4440
      - SERVER_HOS
      - JDBC_DRIVER=mysql
      - DB_HOST=rundeckdb
      - DB_PORT=3306
      - DB_NAME=rundeck
      - DB_USER=rundeck
      - DB_PASSWORD=rundeck

    ports:
      - 4440:4440

networks:
  rundeck-network:
